# hypixel-checker
#
# Checks if anyone has logged into your account and notifies you
#
# Github Repository:
#
#
# Change config by entering your username and api key 👇

USERNAME: voxxal
API_KEY: 9df00a52-b5c9-4888-8067-cb9de2a9fa22
CHECK_FREQUENCY: 1
NOTIFICATIONS: true
